[workspace]
channels = ["conda-forge"]
name = "athenapk"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
scipy = ">=1.16.1,<2"
h5py = ">=3.14.0,<4"
unyt = ">=3.0.4,<4"
yt = ">=4.4.1,<5"
